[env:esp32dev]
platform = espressif32@~6.9.0
board = esp32dev
framework = arduino

monitor_speed = 115200
board_upload.speed = 115200  ; Forces esptool to use a safer baud rate
board_build.filesystem = littlefs
lib_deps =
    waspinator/AccelStepper @ ^1.64   ; (Also update to latest library version)
    https://github.com/tgolla/GCodeParser
